name: Actualise Data

# runs every 2 days at 9 am
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 */2 * *"

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: ./scraper
        run: npm ci
      
      - name: Setup git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Call scraper and update data
        run: |
          npm start --prefix scraper

          CHARACTERS=$(cat ./scraper/output/characters.json)
          CHARACTERS_SCRIPT="import type { ICharacterData } from \"../types\";\n\nexport const CHARACTERS: ICharacterData[] = $CHARACTERS;"
          echo -e "$CHARACTERS_SCRIPT" > ./app/src/data/characters.data.ts
          
          TEAMS=$(cat ./scraper/output/teams.json)
          TEAMS_SCRIPT="import type { ITeamData } from \"../types\";\n\nexport const TEAMS: ITeamData[] = $TEAMS;"
          echo -e "$TEAMS_SCRIPT" > ./app/src/data/teams.data.ts
      
          git add ./scraper/output
          git add ./app/src/data

          git commit -m "ci: Actualise data" && git push || echo "No changes"
        
